---
title: "Exam_systems"
author: "Amandine Godefroy"
format: html
---

# Question 2

[Link github repository](https://github.com/AmandineGodefroy/systems)

# Question 3

```{r configuration}
#| echo: false
#| warning: false
#| message: false

library(here)
library(ggplot2)
library(tidyr)
library(dplyr)
library(vroom)
i_am("systems.Rproj")
```

```{r}
# importation of the main data set
listsystems <- vroom(here("data/listsytems.csv"), locale=locale(decimal_mark=','), show_col_types = FALSE)
```
In this data set we have `r nrow(listsystems)` star systems and `r ncol(listsystems)` variables.
```{r}
if (nrow(listsystems) == 1057) {print('We have the correct number of variables')} else {print('There is a problem with the number of variables')}
if (ncol(listsystems) == 8) {print('We have the correct number of star systems')} else {print('There is a problem with the number of star systems')}
```

```{r}
# Verification that all the numerical variables are recognized as numerical variables
is.numeric(listsystems$Star_key)
is.numeric(listsystems$distance)
is.numeric(listsystems$`EFFECTIVE TEMPERATURE`)
is.numeric(listsystems$`Relative Mass`)
is.numeric(listsystems$`Star Radius`)
is.numeric(listsystems$`RELATIVE LUMINOSITY`)
```
We find that that all the numerical variables are recognised as numerical variables.

# Question 4
```{r}
# Number of missing values for each variable 
na_key <-sum(is.na(listsystems$Star_key))
na_name <-sum(is.na(listsystems$S_NAME))
na_distance <-sum(is.na(listsystems$distance))
na_temperature <-sum(is.na(listsystems$`EFFECTIVE TEMPERATURE`))
na_mass <-sum(is.na(listsystems$`Relative Mass`))
na_radius <-sum(is.na(listsystems$`Star Radius`))
na_luminosity <-sum(is.na(listsystems$`RELATIVE LUMINOSITY`))
na_type <-sum(is.na(listsystems$`Type Of Star`))

```

```{r}
table_listsystems <- listsystems |>
  summarise(
    "Nb of observations" = nrow(listsystems),
    "Nb of variables" = ncol(listsystems),
    "Nb of missing values for the relative luminosity" = na_luminosity,
    "Nb of missing values for the star radius" = na_radius,
    "Nb of missing values for the effective temperature" = na_temperature, "Nb of observations with at least one missing value" = sum(!complete.cases(listsystems))
  )
knitr::kable(table_listsystems)
```
# Question 5

```{r}
#| warning: false
# We use a scatter plot
ggplot(listsystems, aes(x = `Star Radius`, y = `EFFECTIVE TEMPERATURE`)) +
  geom_point(alpha = 0.2) +
  xlab("Star Radius") +
  ylab("Effective Temperature")
```

